name: Extract and Send Emails

on:
  workflow_dispatch:

jobs:
  extract-emails:
    name: Email Extraction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas email-validator

      - name: Run email extraction script
        run: python extract_emails.py

      - name: Find the generated email CSV
        id: find_email_csv
        run: echo "EMAIL_CSV_FILE=$(find extracted_emails_*.csv | head -n 1)" >> $GITHUB_ENV

      - name: Print extracted emails
        run: cat ${{ env.EMAIL_CSV_FILE }}

      - name: Upload extracted emails artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted_emails
          path: ${{ env.EMAIL_CSV_FILE }}

  send-emails:
    name: Email Delivery
    needs: extract-emails
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download extracted emails
        uses: actions/download-artifact@v4
        with:
          name: extracted_emails
          path: extracted_emails

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas email-validator

      - name: Send emails
        env:
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SENDER_EMAIL: "mwalupindim@gmail.com"
        run: python send_emails.py
