name: Scrape Real Estate Listings

on:
  # schedule:
  #   - cron: '0 12 * * *'  # Runs daily at noon UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

      - name: Scrape Property Listings
        run: python scripts/scrape_listings.py

      - name: Send Email with CSV Report
        env:
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAIL: "mwalupindim@gmail.com"
        run: python scripts/send_email.py
