name: Scrape Small Businesses

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  scrape-businesses:
    name: Scrape Businesses Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas beautifulsoup4

      - name: Run scraper
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python scrape_businesses.py

      - name: Find the generated CSV
        id: find_csv
        run: echo "CSV_FILE=$(find . -maxdepth 1 -name 'businesses_*.csv' | head -n 1)" >> $GITHUB_ENV

      - name: Ensure businesses folder exists
        run: mkdir -p businesses

      - name: Move CSV to businesses folder
        run: mv ${{ env.CSV_FILE }} businesses/ || echo "No CSV file to move"

      - name: Display CSV contents
        run: cat businesses/$(basename ${{ env.CSV_FILE }}) || echo "No CSV file found"

      - name: Check if CSV exists in businesses folder
        id: check_csv
        run: |
          if [ -f "businesses/$(basename ${{ env.CSV_FILE }})" ]; then
            echo "UPLOAD_REQUIRED=false" >> $GITHUB_ENV
          else
            echo "UPLOAD_REQUIRED=true" >> $GITHUB_ENV
          fi

      - name: Upload CSV artifact (if not moved)
        if: env.UPLOAD_REQUIRED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: business_data
          path: ${{ env.CSV_FILE }}
